config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   namespace :admin do
    get '/' => 'homes#top'
    root to: "admin/homes#top"
    resources :items
    resources :homes
    resources :customers
    resources :genres
    resources :order_details
    resources :orders
  end
  
   namespace :public do
     delete '/cart_item/destroy_all' => 'cart_items#destroy_all'
     resources :items
     resources :cart_items
     resources :customers
     resources :homes
     get '/orders/confirm' => 'orders#confirm'
     get '/orders/thanks' => 'orders#thanks'
     resources :orders
     post "/orders/confirm" => "orders#confirm"
     resources :shipping_addresses


   end
    get "/customers/quit" => "public/customers#quit"
    get "/customers/withdraw" => "public/customers#withdraw"
    post "/customers/withdraw" => "public/customers#withdraw"
    get "/about" => "public/homes#about", as: "about"
    get "/customers/my_page" => "public/customers#show"
root to: "public/homes#top"

  
end

app/models/address.rb
class Address < ApplicationRecord

belongs_to :customer
def address_display
  '〒' + postal_code + ' ' + shipping_address + ' ' + name
end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item
  ## 小計を求めるメソッド
def subtotal
    item.with_tax_price * amount
end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :orders, dependent: :destroy
         has_many :cart_items, dependent: :destroy
         has_many :addresses, dependent: :destroy
         
end

app/models/genre.rb
class Genre < ApplicationRecord
      has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre
    has_many :cart_items
    has_one_attached :image
    
    #消費税10％加算メソッド
def with_tax_price
    (price * 1.1).floor
end
end

app/models/order.rb
class Order < ApplicationRecord

#アソシエーション

      has_many :order_details, dependent: :destroy
      belongs_to :customer

#enum設定
enum payment_method: { credit_card: 0, transfer: 1 }
enum status: { waiting_for_payment: 0, payment_confirmation: 1, production: 2, shipping_preparation: 3, sent: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
    
    enum making_status: { cannot_be_manufactured: 0, waiting_for_production: 1, production: 2, production_completed: 3 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

    def index
      @customers = Customer.all
    end

    def show
      @customers = Customer.find(params[:id])
    end

    def edit
    @customer = Customer.find(params[:id])
    end
    
    def update
        @customer = Customer.find(params[:id])
  if @customer.update(customer_params)
    redirect_to admin_customer_path
  else
    render :edit
  end
    end


    private
    
    def customer_params
      params.require(:customer).
      permit(:email, :last_name, :first_name, :last_name_kana, 
      :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted)
    end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

def new
  @genre = Genre.new
end

def create
  genre = Genre.new(genre_params)
  genre.save
  redirect_to admin_genres_path
end

def index
  @genre = Genre.new
  @genres = Genre.all
  
end

def edit
  @genre = Genre.find(params[:id])
end

def update
  @genre = Genre.find(params[:id])
  if @genre.update(genre_params)
  redirect_to admin_genres_path
  else
      render :edit
  end
end


private

def genre_params
  params.require(:genre).permit(:name)
end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    @order_details = OrderDetail
    @order_details = OrderDetail.page(params[:page])
  end



end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

def new
  @item = Item.new
end

def create
  @item = Item.new(item_params)
  @item.save
  redirect_to admin_item_path(@item.id)
end

def index
  @items = Item.all 
end

def show
    @items = Item.find(params[:id])
end

def edit
  @item = Item.find(params[:id])
end

def update
  @item = Item.find(params[:id])
  if @item.update(item_params)
    redirect_to admin_items_path
  else
    render :edit
  end
end

  



  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def index
        @order_details = @order.order_details.all
  end
  
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details.all
    @total = 0
  end  
  
  def update
    @order = Order.find(params[:id])
    @total = 0
    @order.update(order_params)
    @order_details = @order.order_details
    if @order.status == "payment_confirmation"
        @order_details.each do |order|
        order.making_status = "waiting_for_production"
        order.save
        end
    end
      redirect_to admin_order_path(@order)
  end
  
  
    private
    
    def order_params
      params.require(:order).permit(:postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method, :status )
    end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      case resource
      when Admin
      admin_path
      when Customer
      root_path
      end
    end

	  def after_sign_up_path_for(resource)
        customers_my_page_path
    end

     def after_sign_out_path_for(resource)
      if resource == :admin
      new_admin_session_path
      else
      root_path
      end
     end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="row">

<h2>会員情報編集</h2>

<div class="col-md-8 offset-md-1"> 

<%= form_with model: @customer, url: admin_customer_path(@customer.id) do |f| %>
  
<table>
<div class="field text-left">
  <tr>
    <th>会員ID</th>
    <td><%= @customer.id %></td>
  </tr>
  
  <tr>
    <th>氏名</th>
    <td><%= f.text_field :last_name %><%= f.text_field :first_name %></td>
  </tr>
      
  <tr>
    <th>フリガナ</th>
    <td><%= f.text_field :last_name_kana %><%= f.text_field :first_name_kana %></td>
  </tr>
  
  <tr>
    <th>郵便番号</th>
    <td><%= f.text_field :postal_code %></td>
  </tr>
  
  <tr>
    <th>住所</th>
    <td><%= f.text_area :address %></td>
  </tr>
  
  <tr>
    <th>電話番号</th>
    <td><%= f.text_field :telephone_number %></td>
  </tr>

  <tr>
    <th>メールアドレス</th>
    <td><%= f.text_field :email %></td>
  </tr>
  
    <tr>
    <th>会員ステータス</th>
    <td><%= f.radio_button :is_deleted, false %> 有効会員 <%= f.radio_button :is_deleted, true %> 退会済み</td>
  </tr>
  
</div> 
</table>
<%= f.submit "変更を保存する", class:"btn btn-primary" %>
<%= link_to :back do %>
  <button>戻る</button>
<% end %>
  
  <% end %>

app/views/admin/customers/index.html.erb
<div class="row">

<h2>会員一覧</h2>


<div class="col-md-8 offset-md-1"> 
<table>
  <thead>
  <tr>
    <th>会員ID</th>
    <th>氏名</th>
    <th>メールアドレス</th>
  </tr>
  </thead>
  
  
  <% @customers.each do |customer| %>
  
  
  <tbody>
    <tr>
      <td><%= customer.id %></td>
      <td><%= link_to admin_customer_path(customer) do %>
        <%= customer.last_name %><%= customer.first_name %>
        <% end %></td>
      <td><%= customer.email %></td>
    </tr>
  </tbody>
  <% end %>
  </table>
</div>
</div>

app/views/admin/customers/show.html.erb
<div class="row">

<h2>会員詳細</h2>

<div class="col-md-8 offset-md-1"> 
<table>
  <tr>
    <th>会員ID</th>
    <td><%= @customers.id %>
    <%if @customers.is_deleted == true %>
    退会済み
    <% else %>
    有効会員
    <% end %>
    </td>
  </tr>
  
  <tr>
    <th>氏名</th>
    <td><%= @customers.last_name %><%= @customers.first_name %></td>
  </tr>
  
  <tr>
    <th>フリガナ</th>
    <td><%= @customers.last_name_kana %><%= @customers.first_name_kana %></td>
  </tr>
  
  <tr>  <tr>
    <th>郵便番号</th>
    <td><%= @customers.postal_code %></td>
  </tr>
  
  <tr>
    <th>住所</th>
    <td><%= @customers.address %></td>
  </tr>
  
  <tr>
    <th>電話番号</th>
    <td><%= @customers.telephone_number %></td>
  </tr>

  <tr>
    <th>メールアドレス</th>
    <td><%= @customers.email %></td>
  </tr>
  

  </table>
      <%= link_to "編集する", edit_admin_customer_path, class:"btn btn-primary" %>
</div>
</div>