config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   namespace :admin do
    get '/' => 'homes#top'
    root to: "admin/homes#top"
    resources :items
    resources :homes
    resources :customers
    resources :genres
    resources :order_details
    resources :orders
  end
  
   namespace :public do
     delete '/cart_item/destroy_all' => 'cart_items#destroy_all'
     resources :items
     resources :cart_items
     resources :customers
     resources :homes
     get '/orders/confirm' => 'orders#confirm'
     get '/orders/thanks' => 'orders#thanks'
     resources :orders
     post "/orders/confirm" => "orders#confirm"
     resources :shipping_addresses


   end
    get "/customers/quit" => "public/customers#quit"
    get "/customers/withdraw" => "public/customers#withdraw"
    post "/customers/withdraw" => "public/customers#withdraw"
    get "/about" => "public/homes#about", as: "about"
    get "/customers/my_page" => "public/customers#show"
root to: "public/homes#top"

  
end

app/models/address.rb
class Address < ApplicationRecord

belongs_to :customer
def address_display
  '〒' + postal_code + ' ' + shipping_address + ' ' + name
end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item
  ## 小計を求めるメソッド
def subtotal
    item.with_tax_price * amount
end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :orders, dependent: :destroy
         has_many :cart_items, dependent: :destroy
         has_many :addresses, dependent: :destroy
         
end

app/models/genre.rb
class Genre < ApplicationRecord
      has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre
    has_many :cart_items
    has_one_attached :image
    
    #消費税10％加算メソッド
def with_tax_price
    (price * 1.1).floor
end
end

app/models/order.rb
class Order < ApplicationRecord

#アソシエーション

      has_many :order_details, dependent: :destroy
      belongs_to :customer

#enum設定
enum payment_method: { credit_card: 0, transfer: 1 }
enum status: { waiting_for_payment: 0, payment_confirmation: 1, production: 2, shipping_preparation: 3, sent: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
    
    enum making_status: { cannot_be_manufactured: 0, waiting_for_production: 1, production: 2, production_completed: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

def new
  @genre = Genre.new
end

def create
  genre = Genre.new(genre_params)
  genre.save
  redirect_to admin_genres_path
end

def index
  @genre = Genre.new
  @genres = Genre.all
  
end

def edit
  @genre = Genre.find(params[:id])
end

def update
  @genre = Genre.find(params[:id])
  if @genre.update(genre_params)
  redirect_to admin_genres_path
  else
      render :edit
  end
end


private

def genre_params
  params.require(:genre).permit(:name)
end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    @order_details = OrderDetail
    @order_details = OrderDetail.page(params[:page])
  end



end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

def new
  @item = Item.new
end

def create
  @item = Item.new(item_params)
  @item.save
  redirect_to admin_item_path(@item.id)
end

def index
  @items = Item.all 
end

def show
    @items = Item.find(params[:id])
end

def edit
  @item = Item.find(params[:id])
end

def update
  @item = Item.find(params[:id])
  if @item.update(item_params)
    redirect_to admin_items_path
  else
    render :edit
  end
end

  



  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def index
        @order_details = @order.order_details.all
  end
  
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details.all
    @total = 0
  end  
  
  def update
    @order = Order.find(params[:id])
    @total = 0
    @order.update(order_params)
    @order_details = @order.order_details
    if @order.status == "payment_confirmation"
        @order_details.each do |order|
        order.making_status = "waiting_for_production"
        order.save
        end
    end
      redirect_to admin_order_path(@order)
  end
  
  
    private
    
    def order_params
      params.require(:order).permit(:postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method, :status )
    end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]


     def after_sign_out_path_for(resource)
      if resource == :admin
      new_admin_session_path
      else
      root_path
      end
     end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      case resource
      when Admin
      admin_path
      when Customer
      root_path
      end
    end

	  def after_sign_up_path_for(resource)
        customers_my_page_path
    end

     def after_sign_out_path_for(resource)
      if resource == :admin
      new_admin_session_path
      else
      root_path
      end
     end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<h1>編集画面</h1>

<%= form_with model: @genre, url: admin_genre_path(@genre.id) do |f| %>

  <h4>ジャンル名</h4>
  <%= f.text_field :name, autofocus: true%>
  
  <%= f.submit "保存" %>
  
<% end %>

app/views/admin/genres/index.html.erb
<div class="row">

<h2>ジャンル追加・一覧</h2>

<%= form_with model: @genre,url: admin_genres_path do |f| %>
  <label for="genre_name">ジャンル</label>
  <%= f.text_field :name %>
  <%= f.submit "追加" %>
  <% end %>


<div class="col-md-8 offset-md-1"> 
<table>
  <tr>
    <th>ジャンル</th>
  </tr>
  <% @genres.each do |genre| %>

  
  <tr>
<td><%= genre.name %></td>
<td><%= link_to "編集", edit_admin_genre_path(genre.id) %> </td>
  </tr>
  

<% end %>
</table>
</div>
</div>

app/views/admin/items/edit.html.erb
<h2>商品編集画面</h2>

<%= form_with model: @item, url:admin_item_path(@item.id) do |f| %>
  
  
    <h4>商品画像
      <%= f.file_field :image, accept: "image/*" %></h4>
  
    <h4>商品名
      <%= f.text_field :name %></h4>

    <h4><%= f.label :ジャンル ,class: "col-xs-3 fix" %>
      <%= f.collection_select :genre_id, Genre.all, :id, :name %></h4>
  
      
    <h4>商品説明文
      <%= f.text_area :introduction %></h4>
      
            
    <h4>税抜き価格
      <%= f.text_field :price %></h4>
      
            
    <h4>販売ステータス

  <%= f.radio_button :is_active, :true %>
  <%= f.label :is_active, "販売中", {value: :true, style: "display: inline-block;"} %>
  <%= f.radio_button :is_active, :false %>
  <%= f.label :is_active, "販売停止", {value: :false, style: "display: inline-block;"} %>

    </h4>  
      
    <%= f.submit '保存' %>
  <% end %>

app/views/admin/items/index.html.erb
<div class="row">



<div class="col-md-8 offset-md-1"> 
<h2>商品一覧</h2>
      <td><%= link_to "新規登録", new_admin_item_path %> </td>

<table>
  <thead>
  <tr>
    <th>商品画像</th>
    <th>商品ID</th>
    <th>商品名</th>
    <th>ジャンル</th>
    <th>商品説明</th>
    <th>税抜き価格</th>
    <th>販売ステータス</th>
  </tr>
  </thead>
  <% @items.each do |item| %>
  <tbody>
    <tr>
  <td><% if item.image.attached? %>
    <%= image_tag item.image, size: "100x100" %>
  <% else %>
    <%= image_tag 'no_image', size: "100x100" %>
  <% end %></td>
      <td><%= item.id %></td>
      <td><%= link_to admin_item_path(item.id) do %>
        <%= item.name %>
        <% end %></td>
      <td><%= item.genre.name %></td>
      <td><%= item.introduction %></td>
      <td><%= item.price %></td>
      <td>                <% if item.is_active %>
                   販売中
                  <% else %>
                  販売停止
                <% end %></td>
    </tr>
  </tbody>
  <% end %>
  </table>
</div>
</div>

app/views/admin/items/new.html.erb
<h1>商品新規登録</h1>

  <%= form_with model: @item, url: admin_items_path do |f| %>
  
    <h4>商品画像
      <%= f.file_field :image, accept: "image/*" %></h4>
  
  
    <h4>商品名
      <%= f.text_field :name %></h4>

    <h4><%= f.label :ジャンル ,class: "col-xs-3 fix" %>
      <%= f.collection_select :genre_id, Genre.all, :id, :name %></h4>
  
      
    <h4>商品説明文
      <%= f.text_area :introduction %></h4>
      
            
    <h4>税抜き価格
      <%= f.text_field :price %></h4>
      
            
    <h4>販売ステータス
  <%= f.radio_button :is_active, :true %>
  <%= f.label :is_active, "販売中", {value: :true, style: "display: inline-block;"} %>
  <%= f.radio_button :is_active, :false %>
  <%= f.label :is_active, "販売停止", {value: :false, style: "display: inline-block;"} %>

    <%= f.submit '商品登録' %>
  <% end %>

app/views/admin/items/show.html.erb
<div class="row">

<h2>商品詳細ページ</h2>

  <% if @items.image.attached? %>
    <%= image_tag @items.image, size: "100x100" %>
  <% else %>
    <%= image_tag 'no_image', size: "200x200" %>
  <% end %>
<div class="col-md-8 offset-md-1"> 
<table>
  <thead>
  <tr>
    <th>商品ID</th>
    <th>商品名</th>
    <th>ジャンル</th>
    <th>商品説明</th>
    <th>税抜き価格</th>
    <th>販売ステータス</th>
  </tr>
  </thead>
  
  <tbody>
    <tr>
      <td><%= @items.id %></td>
      <td><%= @items.name %></td>
      <td><%= @items.genre.name %></td>
      <td><%= @items.introduction %></td>
      <td><%= @items.price %></td>
      <td><% if @items.is_active %>
                   販売中
                  <% else %>
                  販売停止
                <% end %></td>
      <td><%= link_to "編集", edit_admin_item_path(@items.id) %> </td>
    </tr>
  </tbody>

  </table>
</div>
</div>

app/views/admin/orders/show.html.erb
<div class="container takasa">
	<h2><i class="fas fa-box-open"></i>注文履歴詳細</h2><br>
	<div class="row">
		<div class="col-xs-6">
			<p>注文情報</p>
			<table align="left" class="table table-bordered">
				<tr>
					<td>注文日</th>
					<td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
				</tr>
				<tr>
					<td>配送先</td>
					<td>〒<%= @order.postal_code %><br><%= @order.address %><br><%= @order.name %></td>
				</tr>
				<tr>
					<td>支払方法</td>
					<td><%= @order.payment_method_i18n  %></td>
				</tr>
				<tr>
			        <th>注文ステータス</th>
			        <td>  <%= form_with model: @order, url: admin_order_path(@order.id) do |f| %>
			        			<%#間違い= f.select :status,["waiting_for_payment","payment_confirmation","production","shipping_preparation","sent" ] ,style: "margin-top:10px;#" %>
          					<%= f.select :status, Order.statuses_i18n.keys.map{|k| [I18n.t("enums.order.status.#{k}"), k]} %>
          			<%= f.submit "更新" ,class: "btn btn-success btn-sm" %><% end %></td>
        		</tr>
				</tr>
			</table>

			<p>注文内容</p>
				<table class="table table-bordered">
					<tr>
						<th>商品</th>
						<th>単価（税込み)</th>
						<th>個数</th>
						<th>小計</th>
						<th>製作ステータス</th>
					</tr>
					<% @order_details.each do |order_detail| %>
					<tr>
						<td><%= order_detail.item.name %></td>
						<td><%= order_detail.item.with_tax_price.to_s(:delimited) %></td>
						<td><%= order_detail.amount %></td>
						<td><%= (order_detail.item.with_tax_price.to_i * order_detail.amount) %>
							<% @total += (order_detail.item.with_tax_price.to_i * order_detail.amount) %>
						</td>
						
						<td><%= form_with model: order_detail, url: admin_order_detail_path(order_detail), local: true do |f| %>
			        	<%= f.select :making_status, OrderDetail.making_statuses_i18n.keys.map{|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
          			<%= f.submit "更新" ,class: "btn btn-success btn-sm" %><% end %></td>
					</tr>
					<% end %>
				</table>
			</div>
			<div class="col-xs-6">
				<div class="row">
				  <br><p>請求情報</p>
				  <table class="table table-bordered">
					<tr>
						<td>商品合計</td>
						<th><%= @total %></th>
					</tr>
					<tr>
						<td>配送料</td>
						<th>800</th>
					</tr>
					<tr>
						<td>ご請求額</td>
						<th><%= @total + 800 %></th>
					</tr>
				  </table>
		        </div>
		</div>
	</div>
</div>