config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   namespace :admin do
    get '/' => 'homes#top'
    root to: "admin/homes#top"
    resources :items
    resources :homes
    resources :customers
    resources :genres
    resources :order_details
    resources :orders
  end
  
   namespace :public do
     delete '/cart_item/destroy_all' => 'cart_items#destroy_all'
     resources :items
     resources :cart_items
     resources :customers
     resources :homes
     get '/orders/confirm' => 'orders#confirm'
     get '/orders/thanks' => 'orders#thanks'
     resources :orders
     post "/orders/confirm" => "orders#confirm"
     resources :shipping_addresses


   end
    get "/customers/quit" => "public/customers#quit"
    get "/customers/withdraw" => "public/customers#withdraw"
    post "/customers/withdraw" => "public/customers#withdraw"
    get "/about" => "public/homes#about", as: "about"
    get "/customers/my_page" => "public/customers#show"
root to: "public/homes#top"

  
end

app/models/address.rb
class Address < ApplicationRecord

belongs_to :customer
def address_display
  '〒' + postal_code + ' ' + shipping_address + ' ' + name
end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item
  ## 小計を求めるメソッド
def subtotal
    item.with_tax_price * amount
end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :orders, dependent: :destroy
         has_many :cart_items, dependent: :destroy
         has_many :addresses, dependent: :destroy
         
end

app/models/genre.rb
class Genre < ApplicationRecord
      has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre
    has_many :cart_items
    has_one_attached :image
    
    #消費税10％加算メソッド
def with_tax_price
    (price * 1.1).floor
end
end

app/models/order.rb
class Order < ApplicationRecord

#アソシエーション

      has_many :order_details, dependent: :destroy
      belongs_to :customer

#enum設定
enum payment_method: { credit_card: 0, transfer: 1 }
enum status: { waiting_for_payment: 0, payment_confirmation: 1, production: 2, shipping_preparation: 3, sent: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
    
    enum making_status: { cannot_be_manufactured: 0, waiting_for_production: 1, production: 2, production_completed: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

def new
  @genre = Genre.new
end

def create
  genre = Genre.new(genre_params)
  genre.save
  redirect_to admin_genres_path
end

def index
  @genre = Genre.new
  @genres = Genre.all
  
end

def edit
  @genre = Genre.find(params[:id])
end

def update
  @genre = Genre.find(params[:id])
  if @genre.update(genre_params)
  redirect_to admin_genres_path
  else
      render :edit
  end
end


private

def genre_params
  params.require(:genre).permit(:name)
end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    @order_details = OrderDetail
    @order_details = OrderDetail.page(params[:page])
  end



end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

def new
  @item = Item.new
end

def create
  @item = Item.new(item_params)
  @item.save
  redirect_to admin_item_path(@item.id)
end

def index
  @items = Item.all 
end

def show
    @items = Item.find(params[:id])
end

def edit
  @item = Item.find(params[:id])
end

def update
  @item = Item.find(params[:id])
  if @item.update(item_params)
    redirect_to admin_items_path
  else
    render :edit
  end
end

  



  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      case resource
      when Admin
      admin_path
      when Customer
      root_path
      end
    end

	  def after_sign_up_path_for(resource)
        customers_my_page_path
    end

     def after_sign_out_path_for(resource)
      if resource == :admin
      new_admin_session_path
      else
      root_path
      end
     end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>ながのCAKE</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', media: 'all','data-turbolinks-track': 'reload' %>
    
  </head>


  <body>
      <header>

        <nav class="navbar navbar-default shadow-sm">
        <div class="container">
          <div class="row">

          <a class="navbar-brand p-3" href="/"><%= image_tag 'logo4.png' %></a>
          <% if customer_signed_in? %>
          </div>
            <div class="row">
            ようこそ、<%= current_customer.last_name %>さん！
            </div>
          
            <div class="row">
            <%= link_to "マイページ", customers_my_page_path, class:"btn btn-light"  %>
            <%= link_to "商品一覧", public_items_path, class:"btn btn-light" %>
            <%= link_to "カート", public_cart_items_path, class:"btn btn-light" %>
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"btn btn-light" %>
          <% elsif admin_signed_in?%>
            <%= link_to ' 商品一覧', admin_items_path %>
            <%= link_to ' 会員一覧', admin_customers_path %>
            <li><%= link_to ' 注文履歴一覧', admin_path %></li>
            <li><%= link_to ' ジャンル一覧', admin_genres_path %></li>
            <li><%= link_to ' ログアウト', destroy_admin_session_path, method: :delete %></li>
            
        
        <% else %>
          <%= link_to "About", about_path, class:"btn btn-light" %>
          <%= link_to "商品一覧", public_items_path, class:"btn btn-light" %>
          <%= link_to "新規登録", new_customer_registration_path, class:"btn btn-light" %>
          <%= link_to "ログイン", new_customer_session_path, class:"btn btn-light" %>
          <% end %>

        </div>
        </div>
        
        </nav>
        
      </header>


    <%= yield %>
    </div>
  </body>
</html>